### ISSUE TITLE
Breaks some shape keys

### ISSUE THREAD

**Issue by 010Pain010** [killfrenzy96/KillFrenzyAvatarText#1]
Uncertain as to why but every time I install the keyboard it scuffs out specific shape keys on the body mesh but not every shape key.

**Comment by killfrenzy96** [comment]
At this time the KAT system is setup with write defaults disabled. Unfortunately, avatar creators will need to design their animators with write defaults off. The technical reason for this is to eliminate the need to copy parameters using the animator itself, reducing the animator complexity greatly (by over 200x less animator transitions) which greatly improves in-game performance.

If VRChat developers implement a way to copy one parameter to another, I will create an option to have write defaults enabled.

The solution for now is to design your avatar with write defaults off in mind. This means you need to reset your avatar's facial blend shapes by setting them back to 0 after a facial animation is complete. I have attached an example animator for facial expressions.

[FXLayer_WriteDefaultsOff_Example.zip](https://github.com/killfrenzy96/KillFrenzyAvatarText/files/8453980/FXLayer_WriteDefaultsOff_Example.zip)

**Comment by killfrenzy96** [comment]
The new SDK has implemented the ability to copy parameters. This is now planned for implementation.
